# Generated by Django 3.1.1 on 2021-01-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_workout', models.DateTimeField(verbose_name='День тренировки')),
                ('name_of_workout', models.CharField(max_length=200, verbose_name='Название тренировки')),
                ('num_ex', models.IntegerField(verbose_name='Номер упражнения')),
                ('name_of_ex', models.CharField(max_length=200, verbose_name='Название упражнения')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('num_of_repeat', models.IntegerField(verbose_name='Количество повторов')),
                ('numb_of_appr', models.IntegerField(verbose_name='Номер подхода')),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
