# Generated by Django 3.1.4 on 2021-01-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210101_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ex', models.IntegerField(verbose_name='Номер упражнения')),
                ('name_of_ex', models.CharField(max_length=200, verbose_name='Название упражнения')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('num_of_repeat', models.IntegerField(verbose_name='Количество повторов')),
                ('numb_of_appr', models.IntegerField(verbose_name='Номер подхода')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AlterModelOptions(
            name='workout_list',
            options={'verbose_name': 'Тренировочный лист', 'verbose_name_plural': 'Тренировочные листы'},
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_work', models.DateTimeField(verbose_name='День тренировки')),
                ('name_of_work', models.CharField(max_length=200, verbose_name='Название тренировки')),
                ('exercises', models.ManyToManyField(to='main.Exercise')),
            ],
        ),
    ]
